name: BudgetApp
description: "A Flutter project made by Sagnik Bhattacharya for Udemy Flutter course"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sign_button: ^2.0.6
  url_strategy: ^0.3.0
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.3
  cloud_firestore: ^6.1.1
  logger: ^2.6.2
  google_sign_in: ^7.2.0
  firebase_auth: ^6.1.3
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.1.0
  google_fonts: ^6.1.3
  firebase_core: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/
